#!/usr/bin/env python3

import argparse
import platform
import yaml
import sys
import os
import shutil
import shlex
import subprocess
import re
import tempfile
from github import Github
from github import Auth
from github import GithubException
import requests
import semver


MODE_LIST = 1
MODE_INFO = 2
MODE_DOWNLOAD = 3
MODE_UPDATE = 4


# Global data
ARCH = platform.uname()
ARCH_SYSTEM = ARCH.system.lower()
ARCH_MACHINE = ARCH.machine.lower()
ALT_MACHINE_KEYWORDS = {
                        'x86_64' :  ['amd64']
                        }
TAR_EXTENSIONS = ['.tar', '.tar.gz', '.tgz', '.tar.bz2', '.tbz', '.tar.xz', '.txz' ]
TMPDIR = os.path.join(tempfile.gettempdir(), "ghr-util")

def fatal(ret_code, str = None):
  if str is not None:
    print(f"{str}", file=sys.stderr)
  exit(ret_code)


def ensure_binaries(prgs):
  if isinstance(prgs, str):
    if shutil.which(prgs) is None:
      fatal(1, f"{prgs} is required, but not found")
    return True
  elif hasattr(prgs, '__iter__'):
    for prg in prgs:
      ensure_binaries(prg)


def get_machine_keywords():
  keywords = [ ARCH_MACHINE ]
  if ARCH_MACHINE in ALT_MACHINE_KEYWORDS:
    if isinstance(ALT_MACHINE_KEYWORDS[ARCH_MACHINE], str):
      keywords.append(ALT_MACHINE_KEYWORDS[ARCH_MACHINE])
    elif hasattr(ALT_MACHINE_KEYWORDS[ARCH_MACHINE], '__iter__'):
      keywords.extend(ALT_MACHINE_KEYWORDS[ARCH_MACHINE])
  return keywords


def run_prog(prog, args=None, input=None, silent_fail=True):

  if args is not None:
    run_args = [prog]
    run_args.extend(args)
  else:
    run_args = shlex.split(prog)

  try:
    result = subprocess.run(run_args, input=input, capture_output=True, text=True)
  except:
    if not silent_fail:
      fatal(1, f"Failed to execute: {" ".join(run_args)}")
    return None

  if result.returncode != 0 or len(result.stderr) > 0:
    if not silent_fail:
      fatal(1, f"Failed to execute: {" ".join(run_args)}\nReturn Code {result.returncode}\n{result.stderr}")
    return None

  return result.stdout


def sanitize_semver(ver):
  # strip leading zeros
  if ver is not None and len(ver) > 0:
    ver = ver.lstrip('vV').strip()
    cleaned_ver = []
    for s in ver.split('.'):
      s = s.lstrip('0')
      if len(s) > 0:
        cleaned_ver.append(s)
      else:
        cleaned_ver.append('0')
    return ".".join(cleaned_ver)
  return None


def safe_ver(ver):
  if ver is None:
    return 'None'
  return ver


class BasePkgHandler:

  def __init__(self):
    pass

  def get_type(self):
    return 'base'

  def set_pkg(self, name, pkg):
    self.name = name
    self.repo = pkg['repo']

  def get_installed_ver(self):
    return None

  def select_asset(self, candidates):
    return None

  def install(self, fname):
    return False


class DebPkgHandler(BasePkgHandler):

  def __init__(self):
    super().__init__()

  def get_type(self):
    return 'deb'

  def get_installed_ver(self):
    result = run_prog(f"dpkg-query --show {self.name}")
    if result is not None and isinstance(result, str) and len(result) > 0:
      result = result.split()
      if len(result) > 1:
        result = result[1]
        return sanitize_semver(result.split('-')[0])
    return None

  def select_asset(self, candidates):

    # the asset has to be a deb file
    candidates = [ name for name in candidates if name.endswith(".deb")]

    name_tags = {}
    for name in candidates:
      # TODO: cannot break on x86_64
      name_tags[name] = [ s.lower() for s in re.split(r'-|_|\.', name) ]

    # try to filter based on system.  revert is no remaining candidate
    potentials = [ name for name in candidates if ARCH_SYSTEM in name_tags[name] ]
    if len(potentials) > 0 and len(potentials) < len(candidates):
      candidates = potentials

    # machine is a bit more complicated due to multple word matches
    # try the ARCH_MACHINE first
    # try each in turn
    for keyword in get_machine_keywords():
      potentials = [ name for name in candidates if keyword in name_tags[name] ]
      if len(potentials) > 0 and len(potentials) < len(candidates):
        candidates = potentials

    # if we still have too many, try throwing out the musl
    if len(candidates) > 1:
      potentials = [ name for name in candidates if 'musl' not in name_tags[name] ]
      if len(potentials) > 0 and len(potentials) < len(candidates):
        candidates = potentials

    return candidates

  def install(self, fname):
    result = subprocess.run(['sudo', 'bash', '-c', 'apt install ' + fname])
    if result.returncode == 0:
      return True
    return False


class TarballPkgHandler(BasePkgHandler):

  def __init__(self):
    super().__init__()

  def get_type(self):
    return 'tar'

  def set_pkg(self, name, pkg):
    super().set_pkg(self, pkg)
    self.ver_cmd = pkg['ver_cmd']
    self.ver_match = pkg['ver_match']

  def get_installed_ver(self):
    result = run_prog(self.ver_cmd)
    if result is not None and len(result) > 0:
      result = result.split("\n")[0]
      match = re.match(self.ver_match, result)
      if match:
        return sanitize_semver(match.group(1))
    return None

  def select_asset(self, candidates):

    # gotta consider all of the possible tarball extensions
    potentials = []
    for candidate in candidates:
      for ext in TAR_EXTENSIONS:
        if candidate.endswith(ext):
          potentials.append(candidate)
          break
    candidates = potentials

    name_tags = {}
    for name in candidates:
      # TODO: cannot break on x86_64
      name_tags[name] = [ s.lower() for s in re.split(r'-|_|\.', name) ]

    # try to filter based on system.  revert is no remaining candidate
    potentials = [ name for name in candidates if ARCH_SYSTEM in name_tags[name] ]
    if len(potentials) > 0 and len(potentials) < len(candidates):
      candidates = potentials

    # machine is a bit more complicated due to multple word matches
    # try the ARCH_MACHINE first
    # try each in turn
    for keyword in get_machine_keywords():
      potentials = [ name for name in candidates if keyword in name_tags[name] ]
      if len(potentials) > 0 and len(potentials) < len(candidates):
        candidates = potentials

    # if we still have too many, try throwing out the musl
    if len(candidates) > 1:
      potentials = [ name for name in candidates if 'musl' not in name_tags[name] ]
      if len(potentials) > 0 and len(potentials) < len(candidates):
        candidates = potentials

    return candidates

  def install(self, fname):
    return False


def list_package(hdlr, name, pkg):
  hdlr.set_pkg(name, pkg)
  print(f"{hdlr.get_type():<3} {name+":":<15} {safe_ver(hdlr.get_installed_ver()):<10}")


def do_op(op, hdlr, gh, token, name, pkg):

  hdlr.set_pkg(name, pkg)
  installed_ver = hdlr.get_installed_ver()
  print(f"{hdlr.get_type():<3} {name+":":<15} {safe_ver(installed_ver):<10}", end='')

  # get the repo's latest release
  try:
    repo = gh.get_repo(hdlr.repo)
    release = repo.get_latest_release()
  except GithubException as err:
    print(f"\nFailed: Github access for {name} at {hdlr.repo}: {err.status}.")
    return

  if release is None:
    print(f"\nFailed: Release not found for {name} at {hdlr.repo}.")
    return

  released_ver = sanitize_semver(release.tag_name)
  if released_ver is None:
    print(f"\nFailed: Unreadable release version for {name} at {hdlr.repo}.")
    return

  print(f" {safe_ver(released_ver):<10}", end='')
  if installed_ver is None or semver.compare(installed_ver, released_ver) < 0:

    # newer version on github, construct a map of assets
    assets = {}
    for asset in release.get_assets():
      assets[asset.name] = asset

    finalists = hdlr.select_asset(list(assets.keys()))
    if len(finalists) == 0:
      print("None", end='')
    elif len(finalists) > 1:
      print(", ".join(finalists), end='')
    else:
      finalist = finalists[0]
      print(f"{finalist}", end='')

      # if this is just for info, we're all done
      if op != MODE_INFO:
        pass

  print()


def update_package(hdlr, gh, token, name, pkg, do_install, be_verbose):
  pass
    # print(f"Package {name}, Installed: {installed_ver}, released: {released_ver}.")
    # if installed_ver is None or semver.compare(installed_ver, released_ver) < 0:

    # if installed_ver is None:
    #   print(f"Installing {name} version {released_ver}.")
    # else:
    #   print(f"Upgrading {name} version from {installed_ver} to {released_ver}.")

    # # newer version on github
    # assets = {}
    # for asset in release.get_assets():
    #   assets[asset.name] = asset

    # finalists = handler.select_asset(list(assets.keys()))
    # if len(finalists) == 0:
    #   print(f"WARNING: Unable to find matching asset for {name} in release {released_ver}.")
    # else:
    #   if len(finalists) > 1:
    #     print("WARNING: multiple viable candidates. Downloading all candidates and skipping installation.")

    #   for finalist in finalists:
    #     asset = assets[finalist]

    #     if mode == MODE_DRY_RUN:
    #       print(f"  Selected {asset.name} for download", end = "")
    #       if len(finalists) == 1:
    #         print(" and installation", end='')
    #       print(".")
    #     else:

    #       # download asset to tmp directory
    #       os.makedirs(TMPDIR, exist_ok=True)
    #       headers = { "Authorization": f"token {token}", "Accept": "application/octet-stream"}
    #       response = requests.Session().get(asset.url, stream=True, headers=headers)
    #       pathname = os.path.join(TMPDIR, asset.name)
    #       if verbose:
    #         print(f"Downloading {asset.name} ...", end = '')
    #       with open(pathname, "wb") as outfile:
    #         for chunk in response.iter_content(1024*1024):
    #           outfile.write(chunk)
    #       if verbose:
    #         print(" Done")

    #       if mode == MODE_DOWNLOAD_ONLY:
    #         print(f"Package {name} saved as {pathname}.")
    #       elif len(finalists) != 1:
    #         print(f"Installation skipped. Package {name} saved as {pathname}.")
    #       else:
    #         if handler.install(pathname):
    #           os.remove(pathname)
    #         else:
    #           print(f"Installation failed.  Downloaded file at: {pathname}")


def main(args):

    # load the configuration
  if args.file is None:
    args.file = f"{os.environ['XDG_CONFIG_HOME']}" if 'XDG_CONFIG_HOME' in os.environ else f"{os.environ['HOME']}/.config" if 'HOME' in os.environ else ""
    args.file+="/host-config/ghr.yaml"

  cfg = {}
  try:
    with open(args.file) as infile:
      cfg = yaml.safe_load(infile)
  except IOError as err:
    fatal(1, f"{err}")
  except Exception as err:
    fatal(1, f"Unexpected {err=}, {type(err)=}")

  for pkg_type, pkgs in cfg.items():
    hdlr = None
    if pkg_type == 'deb':
      hdlr = DebPkgHandler()
    elif pkg_type == 'tar':
      hdlr = TarballPkgHandler()

    if hdlr is None:
      print(f"Error: unsupported package type: {pkg_type}")
    else:
      for name, pkg in pkgs.items():
        if args.op == MODE_LIST:
          list_package(hdlr, name, pkg)
        else:
          # other ops require an authorized github instance
          auth = Auth.Token(args.token)
          gh = Github(auth=auth)
          do_op(args.op, hdlr, gh, args.token, name, pkg)

  return 0


if __name__ == "__main__":

  map_modes = {
      "list": MODE_LIST,
      "info": MODE_INFO,
      "download": MODE_DOWNLOAD,
      "update": MODE_UPDATE
    }

  ensure_binaries([])
  parser = argparse.ArgumentParser(prog='ghr-util', description='Utility for updating packages/binaries from Github releases', epilog='')
  parser.add_argument("op", choices=list(map_modes), help="Operation to perform.")
  parser.add_argument("--token", default=None, help="Github access token with read privledge (required if op is not 'list')")
  parser.add_argument("file", nargs='?', default=None, help="Configuration file (defaults to $XDG_CONFIG_DIR/config/host-config/ghr.yaml).")
  args = parser.parse_args()
  args.op = map_modes[args.op]
  if args.op != MODE_LIST and (args.token is None or len(args.token) == 0):
    raise argparse.ArgumentError("token is a required argument for info, download, and update operations")
  exit(main(args))
